name: Deploy Flask App to GCP

on:
  push:
    branches:
      - main_v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: | 
        chmod 600 key.pem

    - name: Deploy Code to GCP
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem japdavev5@34.134.16.54 << 'EOF'
        cd /home/truchiwoman-dev
        git pull prod main_v2
        sudo systemctl restart flaskapp
        EOF
